name = "simple-stream-core"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
main = "./worker/index.mjs"
workers_dev = true

[vars]
SUPABASE_URL = "https://hxtlrwibkdyirnvejfor.supabase.co"
CLOUDFLARE_ACCOUNT_ID = "be90b9dfc7dfcf09a335189f4499ef4f"
CLOUDFLARE_STREAM_CUSTOMER_CODE = "y6sra3bzw4qq91m8"
CF_ACCESS_TEAM_DOMAIN = "https://green-morning-4703.cloudflareaccess.com"
CF_ACCESS_AUD = "c0be6912a9528aab4e35bb803271a0619681361d15cb3a3041c629488da324cf"
TRIAL_MAX_REGISTRATIONS_PER_IP = "2"
PUBLIC_APP_URL = "https://simplestreamz.io"

[triggers]
crons = ["*/3 * * * *", "0 * * * *"]

[[kv_namespaces]]
binding = "PLATFORM_SETTINGS"
id = "d4faeaabd2b149d186c4246cde1a8742"
preview_id = "91e64c7e54444be2b2d7e84a59574e8f"

[[send_email]]
name = "EMAIL"

[assets]
directory = "./dist"
binding = "ASSETS"
not_found_handling = "single-page-application"