#!/usr/bin/env python3
"""Build scripts/rebuild-simple-streamz-database.sql from supabase/migrations."""

from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MIGRATIONS_DIR = ROOT / "supabase" / "migrations"
OUT = ROOT / "scripts" / "rebuild-simple-streamz-database.sql"

# Idempotent replacement for the non-idempotent initial migration + realtime add.
SKIP = {
    "20260610000000_initial_schema.sql",
    "20260610000001_player_settings_realtime.sql",
}

HEADER = """\
-- REBUILD Simple Streamz database on project hxtlrwibkdyirnvejfor
-- Run in: https://supabase.com/dashboard/project/hxtlrwibkdyirnvejfor/sql/new
-- Run this ENTIRE file once. Safe to re-run (uses IF NOT EXISTS / drop-if-exists / on conflict).
-- Generated by: python scripts/build-rebuild-sql.py
-- AFTER this: register at https://simplestreamz.io/register then run scripts/promote-admin.sql

"""


def idempotent_tables_and_indexes(sql: str) -> str:
    sql = re.sub(
        r"create table (?!if not exists)(public\.\w+)",
        r"create table if not exists \1",
        sql,
        flags=re.IGNORECASE,
    )
    sql = re.sub(
        r"create unique index (?!if not exists)(\w+)",
        r"create unique index if not exists \1",
        sql,
        flags=re.IGNORECASE,
    )
    sql = re.sub(
        r"create index (?!if not exists)(\w+)",
        r"create index if not exists \1",
        sql,
        flags=re.IGNORECASE,
    )
    return sql


def wrap_realtime_publication(sql: str) -> str:
    pattern = re.compile(
        r"^alter publication supabase_realtime add table (public\.\w+);\s*$",
        re.IGNORECASE | re.MULTILINE,
    )

    def repl(match: re.Match[str]) -> str:
        table = match.group(1)
        return (
            "do $$\n"
            "begin\n"
            f"  alter publication supabase_realtime add table {table};\n"
            "exception when duplicate_object then null;\n"
            "end $$;"
        )

    return pattern.sub(repl, sql)


def add_drop_triggers(sql: str) -> str:
    lines = sql.split("\n")
    out: list[str] = []
    for i, line in enumerate(lines):
        m = re.match(r"create trigger (\w+)", line, re.IGNORECASE)
        if m:
            name = m.group(1)
            table = None
            for j in range(i, min(i + 6, len(lines))):
                tm = re.search(r"\bon\s+((?:public\.)?\w+)", lines[j], re.IGNORECASE)
                if tm:
                    table = tm.group(1)
                    break
            if table:
                drop_line = f"drop trigger if exists {name} on {table};"
                recent = "\n".join(out[-4:]).lower()
                if drop_line.lower() not in recent:
                    out.append(drop_line)
        out.append(line)
    return "\n".join(out)


def add_drop_policies(sql: str) -> str:
    lines = sql.split("\n")
    out: list[str] = []
    for i, line in enumerate(lines):
        m = re.match(r'create policy "([^"]+)"', line, re.IGNORECASE)
        if m:
            name = m.group(1)
            table = None
            tm = re.search(r"\bon\s+((?:public\.)?\w+)", line, re.IGNORECASE)
            if tm:
                table = tm.group(1)
            else:
                for j in range(i + 1, min(i + 5, len(lines))):
                    tm = re.search(r"\bon\s+((?:public\.)?\w+)", lines[j], re.IGNORECASE)
                    if tm:
                        table = tm.group(1)
                        break
            if table:
                drop_line = f'drop policy if exists "{name}" on {table};'
                recent = "\n".join(out[-4:]).lower()
                if drop_line.lower() not in recent:
                    out.append(drop_line)
        out.append(line)
    return "\n".join(out)


def idempotent_subscription_tier_seed(sql: str) -> str:
    marker = "insert into public.subscription_tiers ("
    if marker not in sql or "where not exists" in sql:
        return sql

    start = sql.index(marker)
    # Only transform the first bulk seed (Basic/Pro/Premium), not Enterprise select.
    end = sql.find(");\n\n-- Rebrand default player name", start)
    if end == -1:
        return sql

    block = sql[start : end + 2]
    if "values" not in block.lower():
        return sql

    wrapped = (
        "insert into public.subscription_tiers (\n"
        "  name, description, monthly_price, max_bitrate_mbps, max_concurrent_viewers,\n"
        "  storage_limit_gb, max_stream_keys, has_watermark, support_level, features,\n"
        "  sort_order, is_active, cta_label, is_popular\n"
        ")\n"
        "select v.* from (\n"
        "  values\n"
        + block.split("values", 1)[1].strip().removesuffix(";")
        + "\n) as v(\n"
        "  name, description, monthly_price, max_bitrate_mbps, max_concurrent_viewers,\n"
        "  storage_limit_gb, max_stream_keys, has_watermark, support_level, features,\n"
        "  sort_order, is_active, cta_label, is_popular\n"
        ")\n"
        "where not exists (\n"
        "  select 1 from public.subscription_tiers t where t.name = v.name\n"
        ");"
    )

    return sql[:start] + wrapped + sql[end + 2 :]


def transform(sql: str) -> str:
    sql = idempotent_tables_and_indexes(sql)
    sql = wrap_realtime_publication(sql)
    sql = add_drop_triggers(sql)
    sql = add_drop_policies(sql)
    sql = idempotent_subscription_tier_seed(sql)
    return sql


def main() -> None:
    files = sorted(MIGRATIONS_DIR.glob("*.sql"))
    parts = [HEADER]
    for path in files:
        if path.name in SKIP:
            continue
        body = path.read_text(encoding="utf-8")
        parts.append(f"\n-- ========== {path.name} ==========\n\n")
        parts.append(transform(body))

    OUT.write_text("".join(parts), encoding="utf-8")
    migration_count = sum(1 for p in parts if p.startswith("\n-- =========="))
    print(f"Wrote {OUT} ({migration_count} migrations, skipped {len(SKIP)})")


if __name__ == "__main__":
    main()